### PR TITLE
example bug fixes

### PR DESCRIPTION
**Pull request by yindia**

### CODE REVIEW

**Comment by axic** [comment]
@cdetrio @holgerd77 @jwasinger I'd suggest removing the examples from this repo as they are severely outdated and this only meant as a meta package for backwards compatibility reasons. Not sure that is still a valid reason to have it.

**Comment by yindia** [comment]
@axic Now they are working now so we can keep them here

**Comment by holgerd77** [comment]
@axic is this library meant to be outdated or is this still in use somewhere?

**Comment by axic** [comment]
@evalsocket the networking example is definitely "broken" given the networking doesn't work :)

@holgerd77 I don't think anyone uses it. It was the original library, but then split into the individual repos and not remained as a "meta package", though the browserified part was moved to https://github.com/ethereumjs/browser-builds so I'd assume this repo is not of much use at all.

**Comment by holgerd77** [comment]
@evalsocket Sorry, this wasn't really clear, that this repo is not used any more (especially with all the GitHub stars), thanks for the PR anyhow. I will close this now.

**Pull request closed without merging**
